# This template contains steps to build MsQuic WPA plugin.

jobs:
- job: build_quictrace
  displayName: Any CPU
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self

  - task: NuGetCommand@2
    displayName: Nuget Restore
    inputs:
      restoreSolution: src\plugins\QuicTrace.sln

  - task: VSBuild@1
    continueOnError: true
    inputs:
      solution: src\plugins\QuicTrace.sln
      platform: Any CPU
      configuration: Debug

  - task: VSBuild@1
    continueOnError: true
    inputs:
      solution: src\plugins\QuicTrace.sln
      platform: Any CPU
      configuration: Release

  - template: ./upload-artifacts.yml
