# This template contains steps to build quic.dll debugger extension for a single architecture.

parameters:
  arch: ''

jobs:
- job: build_dbgext_${{ parameters.arch }}
  displayName: Build WindDbg Debugger Extension ${{ parameters.arch }}
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    submodules: recursive

  - task: VSBuild@1
    continueOnError: true
    inputs:
      solution: msquic.dbgext.sln
      platform: ${{ parameters.arch }}
      configuration: debug

  - task: VSBuild@1
    continueOnError: true
    inputs:
      solution: msquic.dbgext.sln
      platform: ${{ parameters.arch }}
      configuration: release

  - template: ./upload-artifacts.yml
