#
# Continuous Integration (CI)
# This pipeline builds MsQuic with PGO instrumentation and runs the performance tests with it.
#

trigger: none
pr: none

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

variables:
- name: BuildArgs
  value: -PGO
- name: PerfArgs
  value: -PGO

#
# Builds
#

stages:

- stage: build_windows
  displayName: Build Windows
  dependsOn: []
  jobs:
  # Officially supported configurations.
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: x86
      tls: schannel
      extraBuildArgs: -DisableTest ${{ variables.BuildArgs }}
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: x64
      tls: schannel
      extraBuildArgs: -DisableTest ${{ variables.BuildArgs }}

#
# Performance Tests
#

- stage: performance
  displayName: Performance Testing
  dependsOn:
  - build_windows
  jobs:
  - template: ./templates/run-performance-int.yml
    parameters:
      tls: schannel
      extraArgs: ${{ variables.PerfArgs }}
  - template: ./templates/run-performance-int.yml
    parameters:
      tls: schannel
      arch: x86
      extraArgs: ${{ variables.PerfArgs }}
