#
# Continuous Integration (CI)
# This pipeline builds and runs MsQuic performance tests.
#

trigger: none
pr: none

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

parameters:
- name: protocol
  type: string
  displayName: Protocol
  default: QUIC
  values:
  - QUIC
  - TCPTLS
  - ("QUIC","TCPTLS")
- name: iterations
  type: number
  displayName: Iterations
  default: 5
- name: durationMs
  type: string
  displayName: Duration (ms)
  default: '10000'
- name: rateMbps
  type: string
  displayName: Rate (Mbps)
  default: '(10,50,100)'
- name: bottleneckQueueRatio
  type: string
  displayName: Bottleneck Queue Ratio
  default: '1.0'
- name: rttMs
  type: string
  displayName: RTT (ms)
  default: '50'
- name: pacing
  type: string
  displayName: Pacing
  default: '(0,1)'
- name: logProfile
  type: string
  displayName: Logging Profile
  default: None
  values:
  - None
  - Datapath.Light
  - Performance.Light

stages:

#
# Builds
#

- stage: build_windows
  displayName: Build Windows
  dependsOn: []
  variables:
    runCodesignValidationInjection: false
  jobs:
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: x64
      tls: schannel
      config: Release
      extraBuildArgs: -DisableTest -DisableTools

#
# Performance Tests
#

- stage: performance
  displayName: WAN Performance Testing
  dependsOn:
  - build_windows
  jobs:
  - template: ./templates/run-wanperf.yml
    parameters:
      jobName: wanperf_custom
      displayName: Custom
      protocol: ${{ parameters.protocol }}
      iterations: ${{ parameters.iterations }}
      durationMs: ${{ parameters.durationMs }}
      rateMbps: ${{ parameters.rateMbps }}
      bottleneckQueueRatio: ${{ parameters.bottleneckQueueRatio }}
      rttMs: ${{ parameters.rttMs }}
      pacing: ${{ parameters.pacing }}
      logProfile: ${{ parameters.logProfile }}
