name: CheckDotnet

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

permissions: read-all

jobs:
  validate:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Validate
    runs-on: windows-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d
      with:
        dotnet-version: 6.0.x
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - name: Prepare Machine
      run: scripts/prepare-machine.ps1
      shell: pwsh
    - name: Run DotNet Update
      run: scripts/generate-dotnet.ps1
      shell: pwsh
    - name: Check for Changes
      run: |
        git add .
        git --no-pager diff --exit-code HEAD
